"""Seed script - creates a user and a supplier via the API."""

import requests

contact_infos = [
    {
        "primary_email": "ops@cedar-supply.com",
        "additional_emails": ["billing@cedar-supply.com", "support@cedar-supply.com"],
        "primary_phone": "+972-50-410-1187",
        "contact_person_name": "Dana Levi",
        "contact_person_title": "Operations Manager",
        "contact_person_email": "dana.levi@cedar-supply.com",
        "contact_person_phone": "+972-52-910-2241",
    },
    {
        "primary_email": "contact@negevtraders.co.il",
        "additional_emails": ["accounts@negevtraders.co.il", "cs@negevtraders.co.il"],
        "primary_phone": "+972-50-410-1188",
        "contact_person_name": "Yossi Cohen",
        "contact_person_title": "Head of Procurement",
        "contact_person_email": "yossi.cohen@negevtraders.co.il",
        "contact_person_phone": "+972-52-910-2242",
    },
    {
        "primary_email": "ops@galilee-wholesale.com",
        "additional_emails": ["billing@galilee-wholesale.com", "support@galilee-wholesale.com"],
        "primary_phone": "+972-50-410-1189",
        "contact_person_name": "Noa Shavit",
        "contact_person_title": "Account Manager",
        "contact_person_email": "noa.shavit@galilee-wholesale.com",
        "contact_person_phone": "+972-52-910-2243",
    },
    {
        "primary_email": "office@arava-imports.com",
        "additional_emails": ["finance@arava-imports.com", "support@arava-imports.com"],
        "primary_phone": "+972-50-410-1190",
        "contact_person_name": "Eitan Rosen",
        "contact_person_title": "General Manager",
        "contact_person_email": "eitan.rosen@arava-imports.com",
        "contact_person_phone": "+972-52-910-2244",
    },
    {
        "primary_email": "ops@sharon-distribution.co.il",
        "additional_emails": ["billing@sharon-distribution.co.il", "support@sharon-distribution.co.il"],
        "primary_phone": "+972-50-410-1191",
        "contact_person_name": "Maya Peretz",
        "contact_person_title": "Supplier Relations Lead",
        "contact_person_email": "maya.peretz@sharon-distribution.co.il",
        "contact_person_phone": "+972-52-910-2245",
    },
    {
        "primary_email": "contact@coastal-supplies.com",
        "additional_emails": ["ap@coastal-supplies.com", "help@coastal-supplies.com"],
        "primary_phone": "+972-50-410-1192",
        "contact_person_name": "Lior Ben-David",
        "contact_person_title": "Logistics Coordinator",
        "contact_person_email": "lior.bendavid@coastal-supplies.com",
        "contact_person_phone": "+972-52-910-2246",
    },
    {
        "primary_email": "ops@jordanvalley-trade.co.il",
        "additional_emails": ["billing@jordanvalley-trade.co.il", "support@jordanvalley-trade.co.il"],
        "primary_phone": "+972-50-410-1193",
        "contact_person_name": "Shira Azulay",
        "contact_person_title": "Customer Success Lead",
        "contact_person_email": "shira.azulay@jordanvalley-trade.co.il",
        "contact_person_phone": "+972-52-910-2247",
    },
    {
        "primary_email": "office@urban-bulk.co.il",
        "additional_emails": ["finance@urban-bulk.co.il", "cs@urban-bulk.co.il"],
        "primary_phone": "+972-50-410-1194",
        "contact_person_name": "Omri Katz",
        "contact_person_title": "Business Development",
        "contact_person_email": "omri.katz@urban-bulk.co.il",
        "contact_person_phone": "+972-52-910-2248",
    },
    {
        "primary_email": "ops@tavor-sourcing.com",
        "additional_emails": ["billing@tavor-sourcing.com", "support@tavor-sourcing.com"],
        "primary_phone": "+972-50-410-1195",
        "contact_person_name": "Hila Bar",
        "contact_person_title": "Partnerships Manager",
        "contact_person_email": "hila.bar@tavor-sourcing.com",
        "contact_person_phone": "+972-52-910-2249",
    },
    {
        "primary_email": "contact@eilat-supplyhub.com",
        "additional_emails": ["accounts@eilat-supplyhub.com", "support@eilat-supplyhub.com"],
        "primary_phone": "+972-50-410-1196",
        "contact_person_name": "Amit Shani",
        "contact_person_title": "Operations Director",
        "contact_person_email": "amit.shani@eilat-supplyhub.com",
        "contact_person_phone": "+972-52-910-2250",
    },
    {
        "primary_email": "ops@shomron-wares.co.il",
        "additional_emails": ["billing@shomron-wares.co.il", "help@shomron-wares.co.il"],
        "primary_phone": "+972-50-410-1197",
        "contact_person_name": "Tal Friedman",
        "contact_person_title": "Warehouse Manager",
        "contact_person_email": "tal.friedman@shomron-wares.co.il",
        "contact_person_phone": "+972-52-910-2251",
    },
    {
        "primary_email": "office@karmel-wholesalers.com",
        "additional_emails": ["finance@karmel-wholesalers.com", "support@karmel-wholesalers.com"],
        "primary_phone": "+972-50-410-1198",
        "contact_person_name": "Rotem Golan",
        "contact_person_title": "Finance Lead",
        "contact_person_email": "rotem.golan@karmel-wholesalers.com",
        "contact_person_phone": "+972-52-910-2252",
    },
    {
        "primary_email": "contact@merkaz-trade.co.il",
        "additional_emails": ["ap@merkaz-trade.co.il", "cs@merkaz-trade.co.il"],
        "primary_phone": "+972-50-410-1199",
        "contact_person_name": "Niv Arzi",
        "contact_person_title": "Key Account Manager",
        "contact_person_email": "niv.arzi@merkaz-trade.co.il",
        "contact_person_phone": "+972-52-910-2253",
    },
    {
        "primary_email": "ops@dan-wholesale.com",
        "additional_emails": ["billing@dan-wholesale.com", "support@dan-wholesale.com"],
        "primary_phone": "+972-50-410-1200",
        "contact_person_name": "Yael Shapira",
        "contact_person_title": "Compliance Officer",
        "contact_person_email": "yael.shapira@dan-wholesale.com",
        "contact_person_phone": "+972-52-910-2254",
    },
    {
        "primary_email": "office@haifa-sourcing.co.il",
        "additional_emails": ["finance@haifa-sourcing.co.il", "help@haifa-sourcing.co.il"],
        "primary_phone": "+972-50-410-1201",
        "contact_person_name": "Saar Nissim",
        "contact_person_title": "Supply Chain Lead",
        "contact_person_email": "saar.nissim@haifa-sourcing.co.il",
        "contact_person_phone": "+972-52-910-2255",
    },
    {
        "primary_email": "contact@shfela-distributors.com",
        "additional_emails": ["accounts@shfela-distributors.com", "support@shfela-distributors.com"],
        "primary_phone": "+972-50-410-1202",
        "contact_person_name": "Liat Avraham",
        "contact_person_title": "Customer Support Manager",
        "contact_person_email": "liat.avraham@shfela-distributors.com",
        "contact_person_phone": "+972-52-910-2256",
    },
    {
        "primary_email": "ops@jerusalem-tradehouse.co.il",
        "additional_emails": ["billing@jerusalem-tradehouse.co.il", "cs@jerusalem-tradehouse.co.il"],
        "primary_phone": "+972-50-410-1203",
        "contact_person_name": "Barak Dahan",
        "contact_person_title": "Regional Manager",
        "contact_person_email": "barak.dahan@jerusalem-tradehouse.co.il",
        "contact_person_phone": "+972-52-910-2257",
    },
    {
        "primary_email": "office@triangle-supplies.com",
        "additional_emails": ["finance@triangle-supplies.com", "support@triangle-supplies.com"],
        "primary_phone": "+972-50-410-1204",
        "contact_person_name": "Michal Stern",
        "contact_person_title": "Operations Supervisor",
        "contact_person_email": "michal.stern@triangle-supplies.com",
        "contact_person_phone": "+972-52-910-2258",
    },
    {
        "primary_email": "contact@gev-warehousing.co.il",
        "additional_emails": ["ap@gev-warehousing.co.il", "help@gev-warehousing.co.il"],
        "primary_phone": "+972-50-410-1205",
        "contact_person_name": "Ido Rahamim",
        "contact_person_title": "Logistics Manager",
        "contact_person_email": "ido.rahamim@gev-warehousing.co.il",
        "contact_person_phone": "+972-52-910-2259",
    },
    {
        "primary_email": "ops@plainview-supply.co.il",
        "additional_emails": ["billing@plainview-supply.co.il", "support@plainview-supply.co.il"],
        "primary_phone": "+972-50-410-1206",
        "contact_person_name": "Shaked Mor",
        "contact_person_title": "Commercial Director",
        "contact_person_email": "shaked.mor@plainview-supply.co.il",
        "contact_person_phone": "+972-52-910-2260",
    },
]

company_infos = [
    {
        "legal_name": "Cedar Supply Solutions Ltd.",
        "dba_name": "Cedar Wholesale",
        "business_address": {
            "street_address_1": "14 Rothschild Blvd",
            "street_address_2": "Floor 2",
            "city": "Tel Aviv",
            "state": "Tel Aviv District",
            "zip_code": "6688101",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "3 HaTaasiya St.",
            "street_address_2": "Warehouse A",
            "city": "Petah Tikva",
            "state": "Central District",
            "zip_code": "4951112",
            "country": "IL",
        },
    },
    {
        "legal_name": "Negev Trading Group Ltd.",
        "dba_name": "Negev Traders",
        "business_address": {
            "street_address_1": "8 Ben Gurion Ave",
            "street_address_2": "Suite 410",
            "city": "Be'er Sheva",
            "state": "Southern District",
            "zip_code": "8410402",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "21 HaOman St.",
            "street_address_2": "Logistics Center",
            "city": "Ofakim",
            "state": "Southern District",
            "zip_code": "8752201",
            "country": "IL",
        },
    },
    {
        "legal_name": "Galilee Wholesale Industries Ltd.",
        "dba_name": "Galilee Bulk",
        "business_address": {
            "street_address_1": "5 HaNassi Blvd",
            "street_address_2": None,
            "city": "Nazareth",
            "state": "Northern District",
            "zip_code": "1610001",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "18 Industrial Zone",
            "street_address_2": "Dock 4",
            "city": "Migdal HaEmek",
            "state": "Northern District",
            "zip_code": "2310902",
            "country": "IL",
        },
    },
    {
        "legal_name": "Arava Imports & Logistics Ltd.",
        "dba_name": "Arava Imports",
        "business_address": {
            "street_address_1": "2 Tamar Rd",
            "street_address_2": "Office 12",
            "city": "Eilat",
            "state": "Southern District",
            "zip_code": "8804210",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "7 Port Area",
            "street_address_2": "Hangar B",
            "city": "Eilat",
            "state": "Southern District",
            "zip_code": "8810201",
            "country": "IL",
        },
    },
    {
        "legal_name": "Sharon Distribution Services Ltd.",
        "dba_name": "Sharon Distribution",
        "business_address": {
            "street_address_1": "19 Weizmann St.",
            "street_address_2": "Suite 300",
            "city": "Kfar Saba",
            "state": "Central District",
            "zip_code": "4432201",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "10 HaMelacha St.",
            "street_address_2": "Warehouse C",
            "city": "Hod Hasharon",
            "state": "Central District",
            "zip_code": "4524502",
            "country": "IL",
        },
    },
    {
        "legal_name": "Coastal Supply Chain Ltd.",
        "dba_name": "Coastal Supplies",
        "business_address": {
            "street_address_1": "6 HaYarkon St.",
            "street_address_2": "Floor 5",
            "city": "Netanya",
            "state": "Central District",
            "zip_code": "4241203",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "25 Industrial Rd",
            "street_address_2": "Storage 9",
            "city": "Hadera",
            "state": "Haifa District",
            "zip_code": "3821201",
            "country": "IL",
        },
    },
    {
        "legal_name": "Jordan Valley Trading Ltd.",
        "dba_name": "Jordan Valley Trade",
        "business_address": {
            "street_address_1": "3 Palmach St.",
            "street_address_2": None,
            "city": "Tiberias",
            "state": "Northern District",
            "zip_code": "1420102",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "12 Kibbutz Rd",
            "street_address_2": "Cold Storage",
            "city": "Beit She'an",
            "state": "Northern District",
            "zip_code": "1080101",
            "country": "IL",
        },
    },
    {
        "legal_name": "Urban Bulk Solutions Ltd.",
        "dba_name": "Urban Bulk",
        "business_address": {
            "street_address_1": "45 Ibn Gabirol St.",
            "street_address_2": "Office 21",
            "city": "Tel Aviv",
            "state": "Tel Aviv District",
            "zip_code": "6433402",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "9 HaTaasiya St.",
            "street_address_2": "Dock 7",
            "city": "Bat Yam",
            "state": "Central District",
            "zip_code": "5951203",
            "country": "IL",
        },
    },
    {
        "legal_name": "Tavor Sourcing Group Ltd.",
        "dba_name": "Tavor Sourcing",
        "business_address": {
            "street_address_1": "11 Hatzor St.",
            "street_address_2": "Suite 15",
            "city": "Afula",
            "state": "Northern District",
            "zip_code": "1830204",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "17 Industrial Park",
            "street_address_2": "Unit 3",
            "city": "Yokneam",
            "state": "Northern District",
            "zip_code": "2069201",
            "country": "IL",
        },
    },
    {
        "legal_name": "Eilat Supply Hub Ltd.",
        "dba_name": "Eilat SupplyHub",
        "business_address": {
            "street_address_1": "4 Sheshet HaYamim St.",
            "street_address_2": "Office 5",
            "city": "Eilat",
            "state": "Southern District",
            "zip_code": "8803101",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "16 Logistics Zone",
            "street_address_2": "Hangar D",
            "city": "Eilat",
            "state": "Southern District",
            "zip_code": "8811202",
            "country": "IL",
        },
    },
]

company_infos.extend([
    {
        "legal_name": "Shomron Warehousing Ltd.",
        "dba_name": "Shomron Wares",
        "business_address": {
            "street_address_1": "7 HaRav Kook St.",
            "street_address_2": "Floor 1",
            "city": "Ariel",
            "state": "Judea and Samaria",
            "zip_code": "4483701",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "22 Industrial Park",
            "street_address_2": "Storage Unit A",
            "city": "Barkan",
            "state": "Judea and Samaria",
            "zip_code": "4482901",
            "country": "IL",
        },
    },
    {
        "legal_name": "Karmel Wholesale Group Ltd.",
        "dba_name": "Karmel Wholesalers",
        "business_address": {
            "street_address_1": "18 HaHistadrut Blvd",
            "street_address_2": "Suite 900",
            "city": "Haifa",
            "state": "Haifa District",
            "zip_code": "3326102",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "5 Port Zone",
            "street_address_2": "Dock 12",
            "city": "Haifa",
            "state": "Haifa District",
            "zip_code": "3508401",
            "country": "IL",
        },
    },
    {
        "legal_name": "Merkaz Trade Solutions Ltd.",
        "dba_name": "Merkaz Trade",
        "business_address": {
            "street_address_1": "26 Weizmann St.",
            "street_address_2": "Office 14",
            "city": "Rehovot",
            "state": "Central District",
            "zip_code": "7634503",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "13 Science Park",
            "street_address_2": "Warehouse 6",
            "city": "Ness Ziona",
            "state": "Central District",
            "zip_code": "7403101",
            "country": "IL",
        },
    },
    {
        "legal_name": "Dan Wholesale Logistics Ltd.",
        "dba_name": "Dan Wholesale",
        "business_address": {
            "street_address_1": "9 Begin Rd",
            "street_address_2": "Tower A, Floor 18",
            "city": "Ramat Gan",
            "state": "Tel Aviv District",
            "zip_code": "5252107",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "4 HaTaasiya St.",
            "street_address_2": "Logistics Bay 3",
            "city": "Givatayim",
            "state": "Tel Aviv District",
            "zip_code": "5340402",
            "country": "IL",
        },
    },
    {
        "legal_name": "Haifa Sourcing Partners Ltd.",
        "dba_name": "Haifa Sourcing",
        "business_address": {
            "street_address_1": "31 Allenby Rd",
            "street_address_2": "Office 210",
            "city": "Haifa",
            "state": "Haifa District",
            "zip_code": "3348201",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "15 Check Post",
            "street_address_2": "Warehouse 11",
            "city": "Nesher",
            "state": "Haifa District",
            "zip_code": "3688401",
            "country": "IL",
        },
    },
    {
        "legal_name": "Shfela Distribution Network Ltd.",
        "dba_name": "Shfela Distributors",
        "business_address": {
            "street_address_1": "12 Herzl St.",
            "street_address_2": "Suite 6",
            "city": "Ramla",
            "state": "Central District",
            "zip_code": "7243102",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "19 Logistics Blvd",
            "street_address_2": "Dock F",
            "city": "Lod",
            "state": "Central District",
            "zip_code": "7121201",
            "country": "IL",
        },
    },
    {
        "legal_name": "Jerusalem Trade House Ltd.",
        "dba_name": "Jerusalem TradeHouse",
        "business_address": {
            "street_address_1": "5 King George St.",
            "street_address_2": "Floor 4",
            "city": "Jerusalem",
            "state": "Jerusalem District",
            "zip_code": "9422904",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "28 Atarot Zone",
            "street_address_2": "Hangar 9",
            "city": "Jerusalem",
            "state": "Jerusalem District",
            "zip_code": "9780101",
            "country": "IL",
        },
    },
    {
        "legal_name": "Triangle Supply Services Ltd.",
        "dba_name": "Triangle Supplies",
        "business_address": {
            "street_address_1": "16 Main Rd",
            "street_address_2": "Office 3",
            "city": "Tira",
            "state": "Central District",
            "zip_code": "4494101",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "7 Industrial Row",
            "street_address_2": "Warehouse 2",
            "city": "Tayibe",
            "state": "Central District",
            "zip_code": "4454202",
            "country": "IL",
        },
    },
    {
        "legal_name": "Gev Warehousing Solutions Ltd.",
        "dba_name": "Gev Warehousing",
        "business_address": {
            "street_address_1": "22 Negev Rd",
            "street_address_2": "Suite 18",
            "city": "Dimona",
            "state": "Southern District",
            "zip_code": "8610203",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "3 Logistics Way",
            "street_address_2": "Storage Block C",
            "city": "Yeruham",
            "state": "Southern District",
            "zip_code": "8055101",
            "country": "IL",
        },
    },
    {
        "legal_name": "Plainview Supply Group Ltd.",
        "dba_name": "Plainview Supply",
        "business_address": {
            "street_address_1": "11 Valley Rd",
            "street_address_2": "Office 7",
            "city": "Rosh Pina",
            "state": "Northern District",
            "zip_code": "1200001",
            "country": "IL",
        },
        "shipping_address": {
            "street_address_1": "14 Upper Galilee Park",
            "street_address_2": "Unit 5",
            "city": "Hatzor HaGlilit",
            "state": "Northern District",
            "zip_code": "1234501",
            "country": "IL",
        },
    },
])

business_infos = [
    {
        "facebook_url": "https://facebook.com/cedar.supply",
        "instagram_handle": "cedar_supply",
        "twitter_handle": "cedar_supply",
        "linkedin_url": "https://linkedin.com/company/cedar-supply",
        "timezone": "Asia/Jerusalem",
        "support_email": "support@cedar-supply.com",
        "support_phone": "+972-3-600-1101",
    },
    {
        "facebook_url": "https://facebook.com/negev.traders",
        "instagram_handle": "negev_traders",
        "twitter_handle": "negev_traders",
        "linkedin_url": "https://linkedin.com/company/negev-traders",
        "timezone": "Asia/Jerusalem",
        "support_email": "help@negevtraders.co.il",
        "support_phone": "+972-8-600-1102",
    },
    {
        "facebook_url": "https://facebook.com/galilee.bulk",
        "instagram_handle": "galilee_bulk",
        "twitter_handle": "galilee_bulk",
        "linkedin_url": "https://linkedin.com/company/galilee-bulk",
        "timezone": "Asia/Jerusalem",
        "support_email": "service@galilee-wholesale.com",
        "support_phone": "+972-4-600-1103",
    },
    {
        "facebook_url": "https://facebook.com/arava.imports",
        "instagram_handle": "arava_imports",
        "twitter_handle": "arava_imports",
        "linkedin_url": "https://linkedin.com/company/arava-imports",
        "timezone": "Asia/Jerusalem",
        "support_email": "cs@arava-imports.com",
        "support_phone": "+972-8-600-1104",
    },
    {
        "facebook_url": "https://facebook.com/sharon.distribution",
        "instagram_handle": "sharon_distribution",
        "twitter_handle": "sharon_dist",
        "linkedin_url": "https://linkedin.com/company/sharon-distribution",
        "timezone": "Asia/Jerusalem",
        "support_email": "support@sharon-distribution.co.il",
        "support_phone": "+972-9-600-1105",
    },
    {
        "facebook_url": "https://facebook.com/coastal.supplies",
        "instagram_handle": "coastal_supplies",
        "twitter_handle": "coastal_supply",
        "linkedin_url": "https://linkedin.com/company/coastal-supplies",
        "timezone": "Asia/Jerusalem",
        "support_email": "help@coastal-supplies.com",
        "support_phone": "+972-9-600-1106",
    },
    {
        "facebook_url": "https://facebook.com/jordanvalley.trade",
        "instagram_handle": "jordanvalley_trade",
        "twitter_handle": "jv_trade",
        "linkedin_url": "https://linkedin.com/company/jordan-valley-trade",
        "timezone": "Asia/Jerusalem",
        "support_email": "support@jordanvalley-trade.co.il",
        "support_phone": "+972-4-600-1107",
    },
    {
        "facebook_url": "https://facebook.com/urban.bulk",
        "instagram_handle": "urban_bulk",
        "twitter_handle": "urban_bulk",
        "linkedin_url": "https://linkedin.com/company/urban-bulk",
        "timezone": "Asia/Jerusalem",
        "support_email": "service@urban-bulk.co.il",
        "support_phone": "+972-3-600-1108",
    },
    {
        "facebook_url": "https://facebook.com/tavor.sourcing",
        "instagram_handle": "tavor_sourcing",
        "twitter_handle": "tavor_source",
        "linkedin_url": "https://linkedin.com/company/tavor-sourcing",
        "timezone": "Asia/Jerusalem",
        "support_email": "help@tavor-sourcing.com",
        "support_phone": "+972-4-600-1109",
    },
    {
        "facebook_url": "https://facebook.com/eilat.supplyhub",
        "instagram_handle": "eilat_supplyhub",
        "twitter_handle": "eilat_supply",
        "linkedin_url": "https://linkedin.com/company/eilat-supplyhub",
        "timezone": "Asia/Jerusalem",
        "support_email": "support@eilat-supplyhub.com",
        "support_phone": "+972-8-600-1110",
    },

    {
        "facebook_url": "https://facebook.com/shomron.wares",
        "instagram_handle": "shomron_wares",
        "twitter_handle": "shomron_wares",
        "linkedin_url": "https://linkedin.com/company/shomron-wares",
        "timezone": "Asia/Jerusalem",
        "support_email": "help@shomron-wares.co.il",
        "support_phone": "+972-2-600-1111",
    },
    {
        "facebook_url": "https://facebook.com/karmel.wholesale",
        "instagram_handle": "karmel_wholesale",
        "twitter_handle": "karmel_wholesale",
        "linkedin_url": "https://linkedin.com/company/karmel-wholesale",
        "timezone": "Asia/Jerusalem",
        "support_email": "support@karmel-wholesalers.com",
        "support_phone": "+972-4-600-1112",
    },
    {
        "facebook_url": "https://facebook.com/merkaz.trade",
        "instagram_handle": "merkaz_trade",
        "twitter_handle": "merkaz_trade",
        "linkedin_url": "https://linkedin.com/company/merkaz-trade",
        "timezone": "Asia/Jerusalem",
        "support_email": "help@merkaz-trade.co.il",
        "support_phone": "+972-8-600-1113",
    },
    {
        "facebook_url": "https://facebook.com/dan.wholesale",
        "instagram_handle": "dan_wholesale",
        "twitter_handle": "dan_wholesale",
        "linkedin_url": "https://linkedin.com/company/dan-wholesale",
        "timezone": "Asia/Jerusalem",
        "support_email": "service@dan-wholesale.com",
        "support_phone": "+972-3-600-1114",
    },
    {
        "facebook_url": "https://facebook.com/haifa.sourcing",
        "instagram_handle": "haifa_sourcing",
        "twitter_handle": "haifa_source",
        "linkedin_url": "https://linkedin.com/company/haifa-sourcing",
        "timezone": "Asia/Jerusalem",
        "support_email": "support@haifa-sourcing.co.il",
        "support_phone": "+972-4-600-1115",
    },
    {
        "facebook_url": "https://facebook.com/shfela.distributors",
        "instagram_handle": "shfela_distributors",
        "twitter_handle": "shfela_dist",
        "linkedin_url": "https://linkedin.com/company/shfela-distributors",
        "timezone": "Asia/Jerusalem",
        "support_email": "help@shfela-distributors.com",
        "support_phone": "+972-8-600-1116",
    },
    {
        "facebook_url": "https://facebook.com/jerusalem.tradehouse",
        "instagram_handle": "jerusalem_tradehouse",
        "twitter_handle": "jtl_trade",
        "linkedin_url": "https://linkedin.com/company/jerusalem-tradehouse",
        "timezone": "Asia/Jerusalem",
        "support_email": "support@jerusalem-tradehouse.co.il",
        "support_phone": "+972-2-600-1117",
    },
    {
        "facebook_url": "https://facebook.com/triangle.supplies",
        "instagram_handle": "triangle_supplies",
        "twitter_handle": "triangle_supply",
        "linkedin_url": "https://linkedin.com/company/triangle-supplies",
        "timezone": "Asia/Jerusalem",
        "support_email": "help@triangle-supplies.com",
        "support_phone": "+972-9-600-1118",
    },
    {
        "facebook_url": "https://facebook.com/gev.warehousing",
        "instagram_handle": "gev_warehousing",
        "twitter_handle": "gev_warehouse",
        "linkedin_url": "https://linkedin.com/company/gev-warehousing",
        "timezone": "Asia/Jerusalem",
        "support_email": "support@gev-warehousing.co.il",
        "support_phone": "+972-8-600-1119",
    },
    {
        "facebook_url": "https://facebook.com/plainview.supply",
        "instagram_handle": "plainview_supply",
        "twitter_handle": "plainview_supply",
        "linkedin_url": "https://linkedin.com/company/plainview-supply",
        "timezone": "Asia/Jerusalem",
        "support_email": "help@plainview-supply.co.il",
        "support_phone": "+972-4-600-1120",
    },
]

banking_infos = [
    {
        "bank_name": "Bank Hapoalim",
        "account_holder_name": "Cedar Supply Solutions Ltd.",
        "account_number_last4": "4101",
    },
    {
        "bank_name": "Leumi Bank",
        "account_holder_name": "Negev Trading Group Ltd.",
        "account_number_last4": "4102",
    },
    {
        "bank_name": "Discount Bank",
        "account_holder_name": "Galilee Wholesale Industries Ltd.",
        "account_number_last4": "4103",
    },
    {
        "bank_name": "Mizrahi-Tefahot",
        "account_holder_name": "Arava Imports & Logistics Ltd.",
        "account_number_last4": "4104",
    },
    {
        "bank_name": "Bank Hapoalim",
        "account_holder_name": "Sharon Distribution Services Ltd.",
        "account_number_last4": "4105",
    },
    {
        "bank_name": "Leumi Bank",
        "account_holder_name": "Coastal Supply Chain Ltd.",
        "account_number_last4": "4106",
    },
    {
        "bank_name": "Discount Bank",
        "account_holder_name": "Jordan Valley Trading Ltd.",
        "account_number_last4": "4107",
    },
    {
        "bank_name": "Mizrahi-Tefahot",
        "account_holder_name": "Urban Bulk Solutions Ltd.",
        "account_number_last4": "4108",
    },
    {
        "bank_name": "Bank Hapoalim",
        "account_holder_name": "Tavor Sourcing Group Ltd.",
        "account_number_last4": "4109",
    },
    {
        "bank_name": "Leumi Bank",
        "account_holder_name": "Eilat Supply Hub Ltd.",
        "account_number_last4": "4110",
    },

    {
        "bank_name": "Discount Bank",
        "account_holder_name": "Shomron Warehousing Ltd.",
        "account_number_last4": "4111",
    },
    {
        "bank_name": "Mizrahi-Tefahot",
        "account_holder_name": "Karmel Wholesale Group Ltd.",
        "account_number_last4": "4112",
    },
    {
        "bank_name": "Bank Hapoalim",
        "account_holder_name": "Merkaz Trade Solutions Ltd.",
        "account_number_last4": "4113",
    },
    {
        "bank_name": "Leumi Bank",
        "account_holder_name": "Dan Wholesale Logistics Ltd.",
        "account_number_last4": "4114",
    },
    {
        "bank_name": "Discount Bank",
        "account_holder_name": "Haifa Sourcing Partners Ltd.",
        "account_number_last4": "4115",
    },
    {
        "bank_name": "Mizrahi-Tefahot",
        "account_holder_name": "Shfela Distribution Network Ltd.",
        "account_number_last4": "4116",
    },
    {
        "bank_name": "Bank Hapoalim",
        "account_holder_name": "Jerusalem Trade House Ltd.",
        "account_number_last4": "4117",
    },
    {
        "bank_name": "Leumi Bank",
        "account_holder_name": "Triangle Supply Services Ltd.",
        "account_number_last4": "4118",
    },
    {
        "bank_name": "Discount Bank",
        "account_holder_name": "Gev Warehousing Solutions Ltd.",
        "account_number_last4": "4119",
    },
    {
        "bank_name": "Mizrahi-Tefahot",
        "account_holder_name": "Plainview Supply Group Ltd.",
        "account_number_last4": "4120",
    },
]

BASE_URL = "http://localhost:8000"


def create_user():
    resp = requests.post(f"{BASE_URL}/users", json={
        "email": "john@example.com",
        "password": "password123",
        "display_name": "John Doe",
    })
    resp.raise_for_status()
    data = resp.json()
    print(f"User created: {data['id']} ({data['email']})")
    return data


def create_supplier(index: int):
    resp = requests.post(f"{BASE_URL}/suppliers", json={
        "password": "password123",
        "contact_info": contact_infos[index],
        "company_info": company_infos[index],
        "business_info": business_infos[index],
        "banking_info": banking_infos[index],
    })
    resp.raise_for_status()
    data = resp.json()
    print(f"Supplier [{index + 1}/20] created: {data['id']} ({data['legal_name']})")
    return data


if __name__ == "__main__":
    user = create_user()

    suppliers = []
    for i in range(20):
        suppliers.append(create_supplier(i))

    print(f"\nDone. 1 user + {len(suppliers)} suppliers created.")
